version: 2
project_name: kush
before:
  hooks:
    - go mod download

builds:
  - id: client
    dir: .
    main: .
    binary: kush
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.date={{.CommitDate}}
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - arm64

release:
  prerelease: "true"

archives:
  - wrap_in_directory: true
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'


changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

homebrew_casks:
  - name: kush
    repository:
      owner: grimdork
      name: homebrew-tools
    commit_author:
      name: grimdork
      email: github@grimdork.net
    homepage: "https://github.com/grimdork/kush"
    description: "Kubernetes utility shell"
    license: MIT

signs:
  - id: gpg-sign
    cmd: gpg
    args:
      - --batch
      - --pinentry-mode
      - loopback
      - --local-user
      - "{{ .Env.GPG_FINGERPRINT }}"
      - --output
      - "${signature}"
      - --detach-sign
      - "${artifact}"
    artifacts: binary
